# Form implementation generated from reading ui file 'UI_Factura.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UIFactura(object):
    def setupUi(self, UIFactura):
        UIFactura.setObjectName("UIFactura")
        UIFactura.resize(426, 407)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UIFactura.sizePolicy().hasHeightForWidth())
        UIFactura.setSizePolicy(sizePolicy)
        UIFactura.setMinimumSize(QtCore.QSize(426, 0))
        UIFactura.setMaximumSize(QtCore.QSize(426, 16777215))
        self.btnCrearFactura = QtWidgets.QPushButton(UIFactura)
        self.btnCrearFactura.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.btnCrearFactura.setObjectName("btnCrearFactura")
        self.lstFacturas = QtWidgets.QListView(UIFactura)
        self.lstFacturas.setGeometry(QtCore.QRect(10, 190, 401, 192))
        self.lstFacturas.setObjectName("lstFacturas")
        self.layoutWidget = QtWidgets.QWidget(UIFactura)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 126))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.txtidfactura = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtidfactura.setReadOnly(False)
        self.txtidfactura.setObjectName("txtidfactura")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtidfactura)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.txtNombreCliente = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNombreCliente.setObjectName("txtNombreCliente")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNombreCliente)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.txtMontoFactura = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtMontoFactura.setObjectName("txtMontoFactura")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMontoFactura)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.dtFechaFactura = QtWidgets.QDateEdit(self.layoutWidget)
        self.dtFechaFactura.setObjectName("dtFechaFactura")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dtFechaFactura)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.cmbEstado = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbEstado.setObjectName("cmbEstado")
        self.cmbEstado.addItem("")
        self.cmbEstado.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cmbEstado)

        self.retranslateUi(UIFactura)
        QtCore.QMetaObject.connectSlotsByName(UIFactura)

    def retranslateUi(self, UIFactura):
        _translate = QtCore.QCoreApplication.translate
        UIFactura.setWindowTitle(_translate("UIFactura", "Gestión facturas"))
        self.btnCrearFactura.setText(_translate("UIFactura", "Crear factura"))
        self.label.setText(_translate("UIFactura", "Numero de factura"))
        self.txtidfactura.setPlaceholderText(_translate("UIFactura", "Ingresar numero de factura"))
        self.label_2.setText(_translate("UIFactura", "Cliente"))
        self.label_3.setText(_translate("UIFactura", "Monto"))
        self.label_4.setText(_translate("UIFactura", "Registro"))
        self.label_5.setText(_translate("UIFactura", "Estado"))
        self.cmbEstado.setItemText(0, _translate("UIFactura", "Activo"))
        self.cmbEstado.setItemText(1, _translate("UIFactura", "Inactivo"))
